/******************************************************************************
 ** File Name:      tasks_def.h                                               *
 ** Author:         Tracy Zhang                                               *
 ** Date:           2010-09-28                                                *
 ** Copyright:      Copyright 2001-2010 by Spreadtrum Communications,Inc.     *
 **                 All Rights Reserved.                                      *
 **                 This software is supplied under the terms of a license    *
 **                 agreement or non-disclosure agreement with Spreadtrum.    *
 **                 Passing on and copying of this document,and communication *
 **                 of its contents is not permitted without prior written    *
 **                 authorization.                                            *
 ** Description:    It contains the structure and enum generated by SDL.
 ******************************************************************************

 ******************************************************************************
 **                        Edit History                                       *
 ** --------------------------------------------------------------------------*
 ** Date           Name             Description                               *
 **---------------------------------------------------------------------------*
 ** 2010-09-28     Tracy Zhang      Create.                                   *
 ******************************************************************************/
#ifndef _TASKS_DEF_H
#define _TASKS_DEF_H

#if defined(PRODUCT_DM) || defined(TIANLONG_MOCOR)
#define CUSTOMIZED_STATIC_TASKS   \
    P_DLR, \
    P_GMM, \
    P_Llmain, \
    P_RRC, \
    P_RlRouter, \
    P_SCT, \
    P_SMmain, \
    P_SNDCPMain, \
    P_cmrouter, \
    P_MAC, \
    P_processMM, \
    P_rlc, 


#define CUSTOMIZED_DYNAMIC_TASKS   \
    P_DLC, \
    P_Llentity, \
    P_SNDCPEntity,

#else  /* else of PRODUCT_DM*/

#if defined(_SUPPORT_GPRS_) || defined(GPRS_SUPPORT)
#include "tasks_def_gsmgprs.h"
#else
#include "tasks_def_gsmonly.h"
#endif

#endif  /* end of PRODUCT_DM*/

#endif

 
