/******************************************************************************
 ** Copyright:  Copyright 2001-2010 by Spreadtrum Communications,Inc.         *
 **             All Rights Reserved.                                          *
 **             This software is supplied under the terms of a license        *
 **             agreement or non-disclosure agreement with Spreadtrum.        *
 **             Passing on and copying of this document,and communication     *
 **             of its contents is not permitted without prior written        *
 **             authorization.                                                *
 **                                                                           *
 ** ===========================================================================
 **
 **     Generated by code_adapter.Thu Nov 25 11:36:21 2010
 **
 *******************************************************************************/


#ifndef __TASKS_DEF_H__

#define __TASKS_DEF_H__

#define CUSTOMIZED_STATIC_TASKS   \
    P_cmrouter, \
    P_DLR, \
    P_GMM, \
    P_Llmain, \
    P_MAC, \
    P_processMM, \
    P_rlc, \
    P_RlRouter, \
    P_RRC, \
    P_SCT, \
    P_SMmain, \
    P_SNDCPMain, 


#define CUSTOMIZED_DYNAMIC_TASKS   \
    P_ccentity, \
    P_SmsCmEntity, \
    P_ssentity, \
    P_DLC, \
    P_RlEntity, 


#endif /*__TASKS_DEF_H__*/
